"""Init migrations

Revision ID: 9adb530f77fe
Revises:
Create Date: 2025-07-08 00:20:19.676208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9adb530f77fe"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tg_uid", sa.Integer(), nullable=False),
        sa.Column("habits", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("completed", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("repeat_number", sa.Integer(), nullable=True),
        sa.Column("date_changed", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_tg_uid"), "user", ["tg_uid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_tg_uid"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
